name = "awesome-proxy"
main = "worker.js"
compatibility_date = "2024-09-01"

# 绑定现有的 Cloudflare D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "nodes-db"
database_id = "3b55a783-16d9-4f31-bd9f-312972752269"
